# This workflow will build and deploy your Flutter web app to GitHub Pages
# Place this file in .github/workflows/gh-pages.yml

name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href=/${{ github.event.repository.name }}/

      # - name: Upload GitHub Pages artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: ./build/web

      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4.0.5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

